import type { Locale } from "@/modules/i18n/translations";

const copy = {
  sr: {
    title: "Stvarna cena do magacina u Srbiji",
    description: "Unesite sve troškove od dobavljača u Kini do prijema robe u Srbiji.",
    goodsCost: "Vrednost robe",
    chinaDomesticTransport: "Transport unutar Kine",
    internationalTransport: "Međunarodni transport",
    insurance: "Osiguranje transporta",
    customsBroker: "Špediter i carinjenje",
    customsDuty: "Carina",
    vat: "PDV",
    inspection: "Kontrola robe / inspekcija",
    storage: "Skladištenje",
    other: "Ostali troškovi",
    sellingPrice: "Planirana prodajna cena",
    transportConfirmed: "Transportni troškovi su potvrđeni ponudom špeditera",
    customsConfirmed: "Carinska stopa je proverena za tarifni broj proizvoda",
    assumptionTitle: "Važne pretpostavke",
    assumptionText: "PDV od 20% je početna pretpostavka za Srbiju. Carinska stopa, tarifni broj i transport moraju biti ručno potvrđeni pre kupovine.",
    reviewWarning: "Nepotvrđene pretpostavke automatski označavaju kalkulaciju kao POTREBNA PROVERA.",
    breakdown: "Struktura troškova",
    transportTotal: "Ukupan transport i osiguranje",
    calculate: "Izračunaj stvarnu cenu",
    calculating: "Računanje...",
    legacyTransport: "Transport",
  },
  de: {
    title: "Tatsächliche Kosten bis zum Lager in Serbien",
    description: "Erfassen Sie alle Kosten vom Lieferanten in China bis zum Wareneingang in Serbien.",
    goodsCost: "Warenwert",
    chinaDomesticTransport: "Inlandstransport in China",
    internationalTransport: "Internationaler Transport",
    insurance: "Transportversicherung",
    customsBroker: "Spediteur und Zollabfertigung",
    customsDuty: "Zoll",
    vat: "Mehrwertsteuer",
    inspection: "Warenkontrolle / Inspektion",
    storage: "Lagerung",
    other: "Sonstige Kosten",
    sellingPrice: "Geplanter Verkaufspreis",
    transportConfirmed: "Transportkosten sind durch ein Speditionsangebot bestätigt",
    customsConfirmed: "Der Zollsatz wurde für die Warentarifnummer geprüft",
    assumptionTitle: "Wichtige Annahmen",
    assumptionText: "20% Mehrwertsteuer ist eine anfängliche Annahme für Serbien. Zollsatz, Tarifnummer und Transport müssen vor dem Kauf manuell bestätigt werden.",
    reviewWarning: "Nicht bestätigte Annahmen markieren die Kalkulation automatisch als PRÜFUNG ERFORDERLICH.",
    breakdown: "Kostenstruktur",
    transportTotal: "Transport und Versicherung gesamt",
    calculate: "Tatsächliche Kosten berechnen",
    calculating: "Berechnung...",
    legacyTransport: "Transport",
  },
  en: {
    title: "True cost to the warehouse in Serbia",
    description: "Enter every cost from the supplier in China to receipt of the goods in Serbia.",
    goodsCost: "Goods value",
    chinaDomesticTransport: "Domestic transport in China",
    internationalTransport: "International transport",
    insurance: "Transport insurance",
    customsBroker: "Freight forwarder and customs clearance",
    customsDuty: "Customs duty",
    vat: "VAT",
    inspection: "Goods inspection",
    storage: "Storage",
    other: "Other costs",
    sellingPrice: "Planned selling price",
    transportConfirmed: "Transport costs are confirmed by a freight quote",
    customsConfirmed: "The customs rate was checked for the product tariff code",
    assumptionTitle: "Important assumptions",
    assumptionText: "20% VAT is an initial assumption for Serbia. The customs rate, tariff code and transport must be manually confirmed before purchase.",
    reviewWarning: "Unconfirmed assumptions automatically mark the calculation as NEEDS REVIEW.",
    breakdown: "Cost breakdown",
    transportTotal: "Total transport and insurance",
    calculate: "Calculate true cost",
    calculating: "Calculating...",
    legacyTransport: "Transport",
  },
} satisfies Record<Locale, Record<string, string>>;

export function getSerbiaLandedCostCopy(locale: Locale) {
  return copy[locale];
}
